cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    Admin:
      email: random@gmail.com
      name: Admin
      password: $2b$12$iLAVkP3cyVHwbRvHnmt/iuRLSafenF1dmoTsxY5jYwZHazp7mBB1y
    CaseMentor3073:
      email: random@gmail.com
      name: CaseMentor3073
      password: $2b$12$ReTRLfDFnTk/cgrL1PB63ORMID5ANMM3W6418WKQZjkepHEbvFWA2
    Test:
      email: random@gmail.com
      name: Test123
      password: $2b$12$t9e4us3fRWlalKFsooZZi.znLYVcUV92r3atnj6ApQq5eXOg..qPa
    password_hasher:
      email: password@gmail.com
      name: password_hasher
      password: $2b$12$/p3teKg7CxIG0I/6LM/T2ubUz5/F8H3sX9IItahR10qFdlcEmryj.
preauthorized:
  emails:
  - mail@gmail.com
